DATALOADER:
  batch_size: 16
  num_workers: 0
EXP:
  DATASET: modelnet40_c
  EXP_ID: modelnet40_c_dgcnn_run_1
  LOSS_NAME: smooth
  METRIC: acc
  MODEL_NAME: dgcnn
  SEED: 1
  TASK: cls
TRAIN:
  l2: 1e-4