ROBUSTINFER:
  ACTIVATE: True 
  METHOD: cvar
  PARAMS:
    CVAR:
      drop_rate: 0.05 
      use_true: False 
      drop_strategy: "drop"
      step: 3
      iter_num: 10
DATALOADER:
  batch_size: 32
  num_workers: 0