DATALOADER:
  batch_size: 32
  num_workers: 0
EXP:
  DATASET: shapenetpart_dgcnn
  EXP_ID: sp_dgcnn_pct
  LOSS_NAME: smooth
  MODEL_NAME: pct
  SEED: 1
  TASK: cls
  OPTIMIZER: pct
TRAIN:
  l2: 1e-4
  learning_rate: 0.0001
